name: Lesson 6

on:
  push:
    branches:
      - lesson-6

jobs:
  cypress_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - name: Run Cypress tests
        run: npx cypress run
      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: frontend/cypress/videos

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Generate deployment package
        run: zip -r deploy.zip build Dockerfile
      - name: '**PLACEHOLDER** Deploy to Elastic Beanstalk.'
        run: echo Placeholder for Deployment